### ISSUE TITLE
getting the migration 'file_name' was not found error

### ISSUE THREAD

**Issue by depo101** [JetBrains/rider-efcore#178]
Hello, 
I'm using ubuntu.
I'm getting the following error on the "ef core command panel" when I want to apply update database command from your plugin. 
I'm using sqlite3 database as a single file db in my web application project.

"The migration '20230805150641_Initial' was not found"

**The command args are below :**
"/usr/lib/dotnet/dotnet ef database update --project WebApplication1/WebApplication1.csproj --startup-project WebApplication1/WebApplication1.csproj --context WebApplication1.SampleDbContext --configuration Debug --no-build 20230805150641_Initial"

If I use directly "dotnet ef" command from the terminal there is no any errors and database updated.

- OS: ubuntu 22.04
- .NET SDK info (installed ones and version used within Rider): 7.0
- Plugin version: 231.1.4
- Rider version: 2023.1.4

**Comment by seclerp** [comment]
Hi, @depo101, thanks for the report. Please give more context, the shape of your project, migrations that are available and also preselected values before hitting OK in the Update Database dialog.

**Comment by depo101** [comment]
Hi @seclerp , I started asp.net mvc project with default template via Rider. I wanted to try sqlite3 database. So I created sample models and then used this riders-efcore plugin for first initial migration. And then I get the error explained above. That's all.

**Comment by seclerp** [comment]
Maybe it's due to "No build" checkbox... Could you try to disable it? Normally, it should be disabled, you don't need it in common cases.
