### ISSUE TITLE
Updating from 232.0.0-rc1 -> 232.1.0

### ISSUE THREAD

**Issue by drjohnsonjr** [JetBrains/rider-efcore#180]
#### Describe the bug

When trying to upgrade the plugin from 232.0.0-rc1 to  232.1.0, on Rider restart, an error dialog appears:

![image](https://github.com/JetBrains/rider-efcore/assets/15238128/61a144b5-e4b6-400f-8151-c16483ae6ac9)

**To Reproduce**

With plugin version  232.0.0-rc1 installed, use the plugins window to upgrade to  232.1.0 and restart rider.

### Environment (please complete the following information):

- OS: Windows 10 enterprise
- .NET SDK info (installed ones and version used within Rider): Installed .NET SDK 6 and 7
- Rider version: 2023.2.1

**Comment by seclerp** [comment]
Hi @drjohnsonjr, this is a known issue related to Rider itself: https://youtrack.jetbrains.com/issue/RIDER-65562

As a workaround, if for some reason it happens again - restart Rider again. If it doesn't work - reinstall the plugin.

I will close this as It's already tracked.
