### ISSUE TITLE
Connection Strings in User Secret no longer shows up in the Update Database dropdown 

### ISSUE THREAD

**Issue by Xor-el** [JetBrains/rider-efcore#182]
#### Describe the bug

Connection Strings in User Secret (secrets.json) no longer show up in the Update Database dropdown when I want to effect my migration changes to the DB.
This used to work in previous versions, was this change intentional?

**To Reproduce**

1. Go to 'Entity Framework Core Tool'
2. Click on 'Update Database'
3. Scroll down to 'Additional Options'
4. Uncheck the "Use default connection of startup project"
5. Select the Connection dropdown
6. connection strings from secrets.json no longer show there, however, those from appsettings.json still show

#### Expected behavior

connection strings from secrets.json should be populated in the dropdown as they used to be.

#### Screenshots

![image](https://github.com/JetBrains/rider-efcore/assets/12124088/ba4c95bf-6b12-4ff1-a243-f9d4886b8018)

### Environment (please complete the following information):

- OS: Windows 10 Home Version 22H2 (OS Build 19045.3324)
- .NET SDK info (installed ones and version used within Rider): 
Installed version:  7.0.400
Used in Rider: .NET Core v7.0.7 x64 (Server GC)
- Plugin version: 232.1.0
- Rider version: JetBrains Rider 2023.2.1 Build #RD-232.9559.61, built on August 22, 2023

#### Additional context

This used to work in previous versions of the plugin, at least 2 versions ago.

**Comment by seclerp** [comment]
By the way, thanks for highlighting the problem with the dialog width when long connection string is presented. It should not shrink so long.

**Comment by Xor-el** [comment]
> Hi @Xor-el, Thanks for the ticket. I'm not able to reproduce the issue: ![image](https://user-images.githubusercontent.com/20597871/264449297-aba216bd-7d27-41f7-9225-4b24af8282ac.png)
> 
> Are you maybe made some changes to the project structure? Can you locate your secrets.json file using `Tools | .NET User Secrets` action?

@seclerp Thanks for the quick response.
I did not make any changes to the project structure recently.
The only thing I did recently on the project was update it to .NET 7.
No idea if that might have caused it.

also, yes I can access my user secrets file (secrets.json) via the method you mentioned above.

here is a screenshot to that effect

![image](https://github.com/JetBrains/rider-efcore/assets/12124088/5e1dfa80-fa77-48a5-b8f6-89e7f52d744f)

**Comment by seclerp** [comment]
Yes, it's an option. You could create a private [issue on YouTrack](https://youtrack.jetbrains.com/newIssue) shared only for JetBrains employees with the project attached in one of the 2 ways:
1. `.zip` file as an attachment to the issue itself
2. Using https://uploads.jetbrains.com

Please use "Rider" as project and "Entity Framework Core" as a subsystem.

**Comment by Xor-el** [comment]
@seclerp Created the issue and attached the project on Youtrack.
added you to the list of people who can act on it.
Can you please confirm that you can access the ticket on YouTrack?

**Comment by seclerp** [comment]
Yes, I have access to it, thanks for all the details and files.

**Comment by seclerp** [comment]
Done in #184
