### ISSUE TITLE
Plugin menu is not appearing

### ISSUE THREAD

**Issue by frasermclean** [JetBrains/rider-efcore#207]
#### Describe the bug

EF Core plugin menu is not appearing under Tools menu. A recent version of Rider seems to have prevented the plugin menu from appearing at all.

**To Reproduce**

1. Follow instructions provided by documentation (Right click Startup or Migrations project).
2. Go to Tools menu
3. See no plugin menu

#### Expected behavior

I would expect that the plugin menu was there like it used to be.

#### Screenshots

![image](https://github.com/JetBrains/rider-efcore/assets/11186885/02873220-389f-4444-bcbc-ae0e431fff14)

### Environment (please complete the following information):

- OS: Windows 11 64bit
- .NET SDK info (installed ones and version used within Rider): 8.0.100
- Plugin version: bundled 233.13135.100
- Rider version: 2023.3.2

**Comment by frasermclean** [comment]
I realised they moved the menu item to the root menu and not under tools any more. Is this what you have?

**Comment by frasermclean** [comment]
I realised they moved the menu item to the root menu and not under tools any more. Is this what you have?

**Comment by seclerp** [comment]
Hi @BenvdStouwe, it has been moved since 2023.3, see the screenshot:

![image](https://github.com/JetBrains/rider-efcore/assets/20597871/f41b7d09-05e5-4eae-a48f-566cb75cc10f)

The same for the Solution node.

You don't need to add it manually into Tools.

**Comment by BenvdStouwe** [comment]
@frasermclean @seclerp thanks! I guess that means I'm just getting old and incompetent...

**Comment by frasermclean** [comment]
> @frasermclean @seclerp thanks! I guess that means I'm just getting old and incompetent...

I saw it directly after I made this issue so felt a bit silly haha. They should probably update the instructions though.
