### ISSUE TITLE
Cannot use update database or add migration.

### ISSUE THREAD

**Issue by atilao4501** [JetBrains/rider-efcore#215]
Hi, i just started to learn .NET and this is my first project. I use JetBrains Rider on linux (Mint) and i was trying to create migrations and update my database using the efcore, but it doesnt work, it says that cant find the dotnet ef. But when i run on my terminal it works.

![image](https://github.com/JetBrains/rider-efcore/assets/107709051/553833b9-19cc-4254-9e1d-069f499f6a31)

translation:

`/home/atila/.dotnet/dotnet ef database update --project GeekShopping.ProductApi/GeekShopping.ProductApi.csproj --startup-project GeekShopping.ProductApi/GeekShopping.ProductApi.csproj --context GeekShopping.ProductApi.Model.Context.MySqlContext --configuration Debug 20240221142417_AddProductDataTableOnDb

**The specified command or file was not found.**

Possible reasons for this include:

* You misspelled a built-in dotnet command.
* You intended to execute a .NET program, but dotnet-ef does not exist.
* You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Process finished with exit code 1.**
`

and thats my PATH:
![image](https://github.com/JetBrains/rider-efcore/assets/107709051/30d5cef9-1196-4a33-9930-1e0f3bc97d4a)

**Comment by seclerp** [comment]
Hi @atilao4501, I can't tell for sure but seems like your shell configuration that Rider uses has the incorrect dotnet tools location.

Please try to troubleshoot the problem using [this guide](https://learn.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues). This is probably not a plugin issue.

Also please check which shell is used in `Settings | Tools | Terminal`. It may be different from Zsh.

**Comment by atilao4501** [comment]
Rider is using Zsh 
![image](https://github.com/JetBrains/rider-efcore/assets/107709051/589b2f63-bb91-4ddc-81db-b7ae574626d3)

and the dotnet CLI path is correct too:
![image](https://github.com/JetBrains/rider-efcore/assets/107709051/ea7c78e4-d430-4695-abfb-1a300828da2e)

i Can use dotnet ef from zsh :
![image](https://github.com/JetBrains/rider-efcore/assets/107709051/98a043c2-cbe1-434f-8c81-cbf352a9f5c7)

but i still cant use in EF CORE.

**Comment by mierzvoj** [comment]
I have identical issue.

**Comment by seclerp** [comment]
Could you folks try to configure `.bashrc` the same way you configured `.zshrc`? It may help as a workaround while fix is coming.

**Comment by atilao4501** [comment]
Tried it and it doesnt work either:
thats my .bashrc
![image](https://github.com/JetBrains/rider-efcore/assets/107709051/5eb7309c-3d92-471a-9164-84e465123e48)

changed the rider terminal to bash:
![image](https://github.com/JetBrains/rider-efcore/assets/107709051/b07eb35c-b7b9-4317-90e3-70eaefca3eaa)

and it doesnt work, 
PS: it does work when i run on a external bash terminal.

**Comment by seclerp** [comment]
Did you tried restarting Rider after changing `.bashrc`?

**Comment by atilao4501** [comment]
yes sir.

**Comment by seclerp** [comment]
From which environment do you start Rider? Is it from a superuser or your regular one? It would be great if you share your launcher configuration if it's possible and presented.

**Comment by atilao4501** [comment]
i open it using my regular user and i installed it using snap:

![image](https://github.com/JetBrains/rider-efcore/assets/107709051/a0ddd177-5e6b-4017-a5b0-8df741356c79)


env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/rider_rider.desktop /snap/bin/rider %f
![image](https://github.com/JetBrains/rider-efcore/assets/107709051/1829612e-7564-4278-a645-8a4a71890b8c)

for translation, it can read and write.

**Comment by seclerp** [comment]
Please try to find the "IDE Scripting Console" in Search Everywhere (Shift, Shift), then type there `System.getenv("PATH")` and press <kbd>Ctrl</kbd> + <kbd>Enter</kbd>. This should dump your `$PATH` variable used while running Rider. Please check if there is a `.tools` folder entry from your `.zshrc`.

**Comment by mierzvoj** [comment]
mine
![image](https://github.com/JetBrains/rider-efcore/assets/55141520/92349df3-6014-4398-bf36-2a96ff39531c)
![Screenshot 2024-02-28 at 15 08 30](https://github.com/JetBrains/rider-efcore/assets/55141520/16177543-b7a9-4532-9406-e670cf657136)

**Comment by mierzvoj** [comment]
> System.getenv("PATH")
[0 ms]=> /usr/bin:/bin:/usr/sbin:/sbin

**Comment by seclerp** [comment]
It means that your user profile environment differs from the one you use in the external terminal and in the terminal tool window inside Rider (it works there because we spawn a new terminal session using a dedicated login shell).

So the only way to solve this issue correctly is to launch Rider from the same environment as your normal user profile-based terminal work.

**Comment by mierzvoj** [comment]
open -a Rider in console 
and EF tool works:
![image](https://github.com/JetBrains/rider-efcore/assets/55141520/fa4c570a-4f00-4cd0-ad64-c04b8ab16659)

**Comment by mierzvoj** [comment]
thank you

**Comment by atilao4501** [comment]
> System.getenv("PATH")
[410 ms]=> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin

thats mine, still doesnt work.  

Tried this but didnt work:
open -a Rider in console
and EF tool works:

**Comment by dex91** [comment]
Hello everybody,

my solution was:

reboot entire system **AFTER** editing the users `.bashrc` file (or any other shell with this ability)..

I am using `Debian 12 bookworm` with `Rider 2024.1.4 (Build #RD-241.18034.76, built on June 23, 2024)`

Perhaps a single logout and re-login _without_ any reboot can do the same.

BTW, you can use `~/.dotnet` instead of `$HOME/.dotnet`, it will result the same ;)

**Comment by mysteryx93** [comment]
I also have this problem. I added the path in `~/.profile`

If I open a terminal (fish terminal, had to add it to PATH in a different way), `echo $PATH` displays it

If I open Rider, open the terminal, `echo $PATH` doesn't show it.

If I open Rider from the terminal, then it works.

Changing Rider terminal to fish doesn't help either.

**Comment by mathisgauthey** [comment]
Same here : 

```
> System.getenv("PATH")
[255 ms]=> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
```

And of course the dotnet tools are listed under my `.zshrc` but rider doesn´t start with these one. I'll try some workarounds evoked here in the meantime.

**Comment by mysteryx93** [comment]
I haven't been successful in altering environment variables, so please keep us posted, with a link to the feature request -- and a work-around that actually works.

**Comment by seclerp** [comment]
Related feature request: #279

**Comment by Desalutar20** [comment]
> A brief guide to resolving command not found or No such file or directory errors when using the EF Core UI tools in JetBrains Rider, especially when it's installed as a Snap package.
> 
> The Problem When launched from the Ubuntu desktop, Rider may not load the environment variables set in your terminal's configuration (~/.bashrc). This prevents it from finding the dotnet executable and the dotnet-ef global tool, causing its integrated EF Core UI tools to fail even when the commands work correctly in a standalone terminal.
> 
> Prerequisites Before you begin, ensure you have the .NET SDK and the EF Core global tool installed.
> 
> Install the .NET SDK: Follow the official Microsoft instructions to install the latest .NET SDK for Ubuntu. After installation, the main executable will typically be located at ~/.dotnet/.
> 
> Install the EF Core Global Tool: Open a terminal and run the following command. This provides the dotnet-ef command.
> 
> `dotnet tool install --global dotnet-ef` This tool will be installed in ~/.dotnet/tools/.
> 
> The Solution: Step-by-Step Step 1: Configure the Session-Wide Environment Profile We need to declare the paths for the .NET SDK and its tools in a place that is read by your entire graphical user session, not just the terminal. The ~/.profile file is the correct place for this.
> 
> Open a terminal.
> 
> Open the .profile file located in your home directory with a text editor. If the file doesn't exist, this command will create it.
> 
> `gedit ~/.profile` (You can replace gedit with nano or any other editor you prefer.)
> 
> Add the following line to the end of the file. This line adds both the main .NET directory and the .NET tools directory to your system's PATH.
> 
> Bash
> 
> `export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"` Save the file and close the text editor.
> 
> Step 2: Apply the New Environment This is the most critical step. For the changes in ~/.profile to take effect for GUI applications, you must log out of your Ubuntu session and log back in. A simple computer restart also achieves this.
> 
> Step 3: Verify the PATH inside Rider Once you have logged back in, you can confirm that Rider is now seeing the correct environment variables.
> 
> Launch Rider from the application icon (not from the terminal).
> 
> Once your project is open, press Ctrl+Shift+A to open the "Find Action" search box.
> 
> Type IDE Scripting Console and open it.
> 
> In the console, type the following command and press Enter:
> 
> `System.getenv("PATH");` Check the output. You should now see /home/your_user/.dotnet and /home/your_user/.dotnet/tools as part of the path string.
> 
> Step 4: Test the EF Core UI With the environment now correctly configured, use the integrated EF Core UI in Rider (e.g., to add a migration or update the database). All commands should now execute successfully.

Thanks
