### ISSUE TITLE
rider-efcore UI does not work with Rider 2024.1.1

### ISSUE THREAD

**Issue by lstatie** [JetBrains/rider-efcore#219]
I am trying to update a few entities in my project and get the error: Not compatible with the version of your running IDE (Rider 2024.1.1)
I see that the Rider EF Core UI has not seen an update since September last year.
Are there any plans to continue support for this plugin going forward?

**Comment by seclerp** [comment]
Hi @lstatie, the plugin has been bundled into the main Rider distribution since Rider 2023.3, so you don't need to install it anymore

![image](https://github.com/JetBrains/rider-efcore/assets/20597871/14e1fbee-dc5a-4bc1-8d9f-73b785273fa0)

**Comment by lstatie** [comment]
Excellent, thank you for the update.

**Comment by seclerp** [comment]
You're welcome! Please note that the Entity Framework Code menu item has been moved to the top-level context menu of the project/solution since 2024.1. Previously it was placed under the Tools submenu.
