### ISSUE TITLE
Any ways to update model from existing database

### ISSUE THREAD

**Issue by tumintu** [JetBrains/rider-efcore#240]
i'm just started to use Rider, is there any ways to update EF model from a existing database.
when i use Visual Studio, i can update my model easily using Model Brower Window(Entity Data Model Designer), but i can't find similar feature in Rider(or plugin).

**Comment by seclerp** [comment]
Hi @tumintu, are you asking about EF or EF Core? This plugin is EF Core-only, the EF support is done directly in Rider and is unrelated to this plugin.

In case you are asking about the EF scaffolding feature, it's not implemented in Rider yet: https://youtrack.jetbrains.com/issue/RIDER-12403/Please-add-support-for-EF-database-first

In case you are asking about the EF Core, could you please dive a little bit into the details? Do you mean the Scaffold DbContext feature?

**Comment by tumintu** [comment]
![update model](https://github.com/user-attachments/assets/e0d1fbcc-a57d-4769-9de8-8df084f57864)
I can't show you my project, so I found this picture online, which is from Visual Studio.
what I mean is [Update Model from Database...] on the menu, I can't find it in Rider.
Did I miss something and not find it, or is the Rider currently lacking this feature?

**Comment by seclerp** [comment]
Hi @tumintu, according to the screenshot, you are asking about EF, not EF Core.

We have a tracking issue which you can follow regarding your request: https://youtrack.jetbrains.com/issue/RIDER-12403/Please-add-support-for-EF-database-first
