### ISSUE TITLE
Azure Functions: Improve usage experience and fix related issues

### ISSUE THREAD

**Issue by jektvik** [JetBrains/rider-efcore#248]
#### Describe the bug

**To Reproduce**

Create an AzureFunctions project. Put your connection string as required in:
local.settings.json
Try applying migration through the EfCore Rider UI

Problem1:
Keep "Use the default connection..." checked.
Try Update the POSTGRES database -> fail due do :
`System.ArgumentException: Host can't be null
   at Npgsql.NpgsqlConnectionStringBuilder.PostProcessAndValidate()
`
Problem2: 
Uncheck the checkbox from Problem 1.
Try to pick Connection from the Connection dropdown -> the list is empty

Problem3:
Enter the connection string manually. This may work but the connection string is blank again on next opening of the EF core window.

#### Expected behavior

Just fix that EfCore tool please to support these workflows.

Has JetBrains tried building Azure Functions through the provided tooling in Rider ? A lot of things don't work like they should, these are just a few examples.

#### Screenshots

![image](https://github.com/user-attachments/assets/fe24acd5-2fc3-496d-8526-6d5ac8f8520f)

### Environment (please complete the following information):

- OS: Win 10
- .NET SDK info (installed ones and version used within Rider): net8.0
- Plugin version: bundled 242.23339.62
- Rider version: JetBrains Rider 2024.2.6
Build #RD-242.23339.62, built on October 8, 2024

#### Additional context

I would suggest that instead of chasing various config files and environment variables where users may be putting that connectionString in their application, the easiest approach for JetBrains would be to simply persist the user input in the Update dialogue between migrations and this would solve most of these ConnectionString detection troubles (I've searched the past Github issues, this isn't the first complaint about this problem)

**Comment by seclerp** [comment]
Hi @jektvik, thanks for the report.

Regarding
> the easiest approach for JetBrains would be to simply persist the user input in the Update dialogue between migrations

This is already done but intentionally disabled by default. You can find the corresponding setting under **Tools | EF Core UI | Autofill additional options**:

<img width="1049" alt="image" src="https://github.com/user-attachments/assets/d9e11f91-a50c-4f13-802d-36e41dd99fc2">

**Comment by jektvik** [comment]
> This is already done but intentionally disabled by default. You can find the corresponding setting under **Tools | EF Core UI | Autofill additional options**:

Good riddance. Thanks. 

Yes this is indeed great but of course useless if one needs to write a bug ticket to learn about the existence of this setting. But the subject feature/settings disoverability is a separate rant to be had elsewhere :]

**Comment by seclerp** [comment]
Regarding
> Problem1:
> Keep "Use the default connection..." checked.
> Try Update the POSTGRES database -> fail due do :
> `System.ArgumentException: Host can't be null at Npgsql.NpgsqlConnectionStringBuilder.PostProcessAndValidate() `

The EF Core plugin relies on **user-installed** `dotnet ef` under the hood. It means that you need to keep your installed `dotnet ef` version in sync with the `Microsoft.EntityFrameworkCore.Design` (or `Tools`) package of your project as they may be incompatible between major releases.

After the command's execution, the terminal output contains the command that had been executed to perform the update action. It can be also observed using the "Preview" button in the dialog's UI before execution.

"Use default connection" means that we will not customize the connection string using the `--connection` parameter, which means that it's up to the app's runtime code to get the connection from the config it knows about.

That said, I would suggest you execute the `dotnet ef database update` command manually and check if it works with your specific scenario. If so, please post the full command, and from which working directory it is being executed.

**Comment by seclerp** [comment]
> if one needs to write a bug ticket to learn about the existence of this setting

I totally agree with you on that point. The settings and other hidden features should be properly documented. I will create an action item for that too.

**Comment by jektvik** [comment]
> Regarding
> 
> > Problem1:
> > Keep "Use the default connection..." checked.
> > Try Update the POSTGRES database -> fail due do :
> > `System.ArgumentException: Host can't be null at Npgsql.NpgsqlConnectionStringBuilder.PostProcessAndValidate() `
> 
> The EF Core plugin relies on **user-installed** `dotnet ef` under the hood. It means that you need to keep your installed `dotnet ef` version in sync with the `Microsoft.EntityFrameworkCore.Design` (or `Tools`) package of your project as they may be incompatible between major releases.
> 
> After the command's execution, the terminal output contains the command that had been executed to perform the update action. It can be also observed using the "Preview" button in the dialog's UI before execution.
> 
> "Use default connection" means that we will not customize the connection string using the `--connection` parameter, which means that it's up to the app's runtime code to get the connection from the config it knows about.
> 
> That said, I would suggest you execute the `dotnet ef database update` command manually and check if it works with your specific scenario. If so, please post the full command, and from which working directory it is being executed.

Thats right, my bad, can't blame JetBrains for this one 🙏That's the migration tolling's fault.

**Comment by seclerp** [comment]
Hi @jektvik, we have written the documentation for the EF Core plugin, you can find it here: https://www.jetbrains.com/help/rider/Entity_Framework_support.html
